namespace IonBlazor.Components;

public struct IonInputEvent
{
    internal IonInputEvent(bool isTrusted)
    {
        IsTrusted = isTrusted;
    }

    /// <summary>
    /// Is <b>true</b> when the event was generated by a user action,
    /// and <b>false</b> when the event was created or modified by a script or dispatcher event
    /// </summary>
    public bool IsTrusted { get; init; }
}